import './globals.css'
import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'

const inter = PT_Sans({weight: ["700", "400"], subsets: ["cyrillic"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
